/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

type InlineResponse200Success struct {
	Exchange *InlineResponse200SuccessExchange `json:"Exchange,omitempty"`
}
