/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

type InlineResponse2001Success struct {
	NSE *InlineResponse200SuccessExchange `json:"NSE,omitempty"`
	BSE *InlineResponse200SuccessExchange `json:"BSE,omitempty"`
}
