/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

type InlineResponse200 struct {
	Success *InlineResponse200Success `json:"Success,omitempty"`
}
