/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

// Order parmaeter for Product GTC
type Gtcmodify struct {
	// Order Number to modify
	GtcOrderNo string `json:"gtcOrderNo,omitempty"`
}
