/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

// Order parmaeter for Product GTC
type Gtcplace struct {
	// Close date for GTC order till which order to be placed in exchange by system.
	CloseDate string `json:"closeDate,omitempty"`
}
