/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

type InlineResponse200SuccessExchange struct {
	Message  string  `json:"message,omitempty"`
	OrderId  float64 `json:"orderId,omitempty"`
	Price    float64 `json:"price,omitempty"`
	Quantity float64 `json:"quantity,omitempty"`
}
