/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

type OrderMisBody struct {
	// Order ID of the order to be modified
	OrderId string `json:"orderId"`
	// Order quantity - specified in same unit as quoted in market depth
	Quantity int32 `json:"quantity,omitempty"`
	// Order Price, non zero positive for limit order and zero for market order
	Price float32 `json:"price,omitempty"`
	// Quantity to be disclosed in order
	DisclosedQuantity int32 `json:"disclosedQuantity,omitempty"`
	// Original open quantity of order
	OriginalOpenQuantity int32 `json:"originalOpenQuantity,omitempty"`
	// Original order price input by client/user.
	OriginalPrice float32 `json:"originalPrice,omitempty"`
	// Trigger price, required for stoploss or supermultiple order
	TriggerPrice float32 `json:"triggerPrice,omitempty"`
	// Validity of the order - GFD, IOC etc
	Validity string `json:"validity,omitempty"`
}
