/*
 * Orders-API
 *
 * Order Placement API's
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package orders

type OrderNormalBody1 struct {
	// Instrument token of the scrip to be traded
	InstrumentToken int64 `json:"instrumentToken,omitempty"`
	// Transaction Type - BUY or SELL
	TransactionType string `json:"transactionType,omitempty"`
	// Order quantity - specified in same unit as quoted in market depth
	Quantity int64 `json:"quantity,omitempty"`
	// Order Price, non zero positive for limit order and zero for market order
	Price float32 `json:"price,omitempty"`
	// Validity of the order - GFD, IOC etc
	Validity string `json:"validity,omitempty"`
	// Variety of the order - REGULAR, AMO, SQUAREOFF - for Super Multiple Orders etc
	Variety string `json:"variety,omitempty"`
	// Quantity to be disclosed in order
	DisclosedQuantity int32 `json:"disclosedQuantity,omitempty"`
	// Trigger price, required for stoploss or supermultiple order
	TriggerPrice float32 `json:"triggerPrice,omitempty"`
	// Tag for this order
	Tag string `json:"tag,omitempty"`
}
