/*
 * Quotes - KSEC
 *
 * This is a sample server for Kotak Trade API - Quote
 *
 * API version: v1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package quotes_ksec

type InlineResponse200DepthBuy struct {
	Price float32 `json:"price,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Orders int32 `json:"orders,omitempty"`
}
