/*
 * Quotes - KSEC
 *
 * This is a sample server for Kotak Trade API - Quote
 *
 * API version: v1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package quotes_ksec

type InlineResponse200Depth struct {
	Buy *InlineResponse200DepthBuy `json:"buy,omitempty"`
	Sell *InlineResponse200DepthBuy `json:"sell,omitempty"`
}
