/*
 * Positions-API
 *
 * Positions API's
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package positions

type Open struct {
	InstrumentToken int64 `json:"instrumentToken,omitempty"`
	// Order Status
	Normal float32 `json:"normal,omitempty"`
	// Order Status
	Supermultiple float32 `json:"supermultiple,omitempty"`
	// Order Status
	Mtf float32 `json:"mtf,omitempty"`
}
