/*
 * Watchlist-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package watchlist

type InlineResponse2006Success struct {
	// Response Message from Service
	Message string `json:"message,omitempty"`
	// Unique Watchlist Id
	WatchlistId float64 `json:"watchlistId,omitempty"`
}
