/*
 * Watchlist-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package watchlist

type InlineResponse2007Success struct {
	// New Watchlist Name
	NewWatchlistName string `json:"newWatchlistName,omitempty"`
	// Unique Watchlist Id
	WatchlistId float64 `json:"watchlistId,omitempty"`
}
