/*
 * Watchlist-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package watchlist

type InlineResponse2004Success struct {
	// Response message from service.
	NewWatchlistName string `json:"newWatchlistName,omitempty"`
	// Renamed Watchlist Id.
	WatchlistId float64 `json:"watchlistId,omitempty"`
}
