/*
 * Reports-KSEC
 *
 * Order Reports API's
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reports

type InlineResponse2001Success struct {
	Exchange        string  `json:"exchange,omitempty"`
	ExchangeTradeId string  `json:"exchangeTradeId,omitempty"`
	ExpiryDate      string  `json:"expiryDate,omitempty"`
	InstrumentName  string  `json:"instrumentName,omitempty"`
	InstrumentToken float64 `json:"instrumentToken,omitempty"`
	InstrumentType  string  `json:"instrumentType,omitempty"`
	IsFNO           string  `json:"isFNO,omitempty"`
	MarketExchange  string  `json:"marketExchange,omitempty"`
	MarketLot       float64 `json:"marketLot,omitempty"`
	Multiplier      float64 `json:"multiplier,omitempty"`
	OptionType      string  `json:"optionType,omitempty"`
	OrderId         float64 `json:"orderId,omitempty"`
	OrderTimestamp  string  `json:"orderTimestamp,omitempty"`
	Price           float64 `json:"price,omitempty"`
	Product         string  `json:"product,omitempty"`
	Quantity        float64 `json:"quantity,omitempty"`
	StatusInfo      string  `json:"statusInfo,omitempty"`
	StatusMessage   string  `json:"statusMessage,omitempty"`
	StrikePrice     float64 `json:"strikePrice,omitempty"`
	TradeId         float64 `json:"tradeId,omitempty"`
	TradeTimestamp  string  `json:"tradeTimestamp,omitempty"`
	TransactionType string  `json:"transactionType,omitempty"`
}
