/*
 * Reports-KSEC
 *
 * Order Reports API's
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200Success struct {
	ActivityTimestamp string `json:"activityTimestamp,omitempty"`
	DisclosedQuantity float64 `json:"disclosedQuantity,omitempty"`
	ExchOrderId string `json:"exchOrderId,omitempty"`
	ExchTradeId string `json:"exchTradeId,omitempty"`
	ExchangeStatus string `json:"exchangeStatus,omitempty"`
	FilledQuantity float64 `json:"filledQuantity,omitempty"`
	Message string `json:"message,omitempty"`
	OrderQuantity float64 `json:"orderQuantity,omitempty"`
	Price float64 `json:"price,omitempty"`
	Status string `json:"status,omitempty"`
	StatusInfo string `json:"statusInfo,omitempty"`
	StatusMessage string `json:"statusMessage,omitempty"`
	TriggerPrice float64 `json:"triggerPrice,omitempty"`
	Validity string `json:"validity,omitempty"`
	Version float64 `json:"version,omitempty"`
}
