/*
 * Reports-KSEC
 *
 * Order Reports API's
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Order History of Order
type History struct {
	Version int64 `json:"version,omitempty"`
	OrderQuantity int32 `json:"orderQuantity,omitempty"`
	Price float64 `json:"price,omitempty"`
	FilledQuantity int32 `json:"filledQuantity,omitempty"`
	ExchangeStatus string `json:"exchangeStatus,omitempty"`
	// Order Status
	Status string `json:"status,omitempty"`
	DisclosedQuantity int32 `json:"disclosedQuantity,omitempty"`
	TriggerPrice int32 `json:"triggerPrice,omitempty"`
	Validity string `json:"validity,omitempty"`
	ExchOrderId string `json:"exchOrderId,omitempty"`
	ExchTradeId string `json:"exchTradeId,omitempty"`
	Message string `json:"message,omitempty"`
	ActivityTimestamp string `json:"activityTimestamp,omitempty"`
}
