/*
 * Reports-KSEC
 *
 * Order Reports API's
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package reports

// Fault Details
type Fault struct {
	// error code
	Code int32 `json:"code,omitempty"`
	// error message
	Message string `json:"message,omitempty"`
	// error description
	Description string `json:"description,omitempty"`
}
