/*
 * Token-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package token

type RevokeBody struct {
	// access token you want to revoke
	Token string `json:"token,omitempty"`
	// (optional)
	TokenTypeHint string `json:"token_type_hint,omitempty"`
}
