/*
 * Token-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package token

type TokenBody struct {
	GrantType string `json:"grant_type,omitempty"`
	// only if grant_type=password
	Username string `json:"username,omitempty"`
	// only if grant_type=password
	Password string `json:"password,omitempty"`
	// only if grant_type=refresh_token
	RefreshToken string `json:"refresh_token,omitempty"`
}
