/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

type InlineResponse2005 struct {
	// Unique token for instrument
	InstrumentToken int32 `json:"instrumentToken,omitempty"`
	// date of contract
	Date string `json:"date,omitempty"`
	// Quantity of purchase
	Quantity float64 `json:"quantity,omitempty"`
	// rate of purchase
	Rate float64 `json:"rate,omitempty"`
	// status of request
	Status string `json:"status,omitempty"`
}
