/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

type PriceforupdateScripwiseBody struct {
	InstrumentToken string `json:"instrumentToken,omitempty"`
	// edit dateformat(dd/mm/yyyy)
	Date string `json:"date,omitempty"`
	Quantity float64 `json:"quantity,omitempty"`
	Price float64 `json:"price,omitempty"`
	// B/S for BUY / SELL 
	OrderType string `json:"orderType,omitempty"`
	TypeOfTransaction string `json:"typeOfTransaction,omitempty"`
}
