/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

type InlineResponse2002SuccessMutualFund struct {
	Debt *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"debt,omitempty"`
	Equity *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"equity,omitempty"`
	Hybrid *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"hybrid,omitempty"`
	Total *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"total,omitempty"`
}
