/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

type InlineResponse2003Success struct {
	Debentures  *InlineResponse2003SuccessDebentures  `json:"debentures,omitempty"`
	ETF         *InlineResponse2003SuccessDebentures  `json:"ETF,omitempty"`
	Equity      *InlineResponse2003SuccessDebentures  `json:"equity,omitempty"`
	Darivatives *InlineResponse2003SuccessDarivatives `json:"darivatives,omitempty"`
	MutualFund  *InlineResponse2003SuccessMutualFund  `json:"mutualFund,omitempty"`
}
