/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

// Equity Profite &amp; Loss Details
type PnlEquity struct {
	// Title of the instrument
	InstrumentType string `json:"instrumentType,omitempty"`
	// Buy Date of the Transaction
	BuyDate string `json:"buyDate,omitempty"`
	// Sell Date of the Transaction
	SellDate string `json:"sellDate,omitempty"`
	// Quantity of the Transaction
	Quantity int32 `json:"quantity,omitempty"`
	// CostBasis of the Transaction
	CostBasis float32 `json:"costBasis,omitempty"`
	// Proceeds of the Transaction
	Proceeds float32 `json:"proceeds,omitempty"`
	// Long Term PNL
	LongTerm float32 `json:"longTerm,omitempty"`
	// Short Term PNL
	ShortTerm float32 `json:"shortTerm,omitempty"`
	// Net Total
	Total float32 `json:"total,omitempty"`
	// Sub Type of Record
	SubType string `json:"subType,omitempty"`
	// Status of Instrument Possible values ACTV, SUSP
	InstrumentStatus string `json:"instrumentStatus,omitempty"`
	// Market Lot of Security.
	MarketLot float64 `json:"marketLot,omitempty"`
	// Sector of the instrument
	Sector string `json:"sector,omitempty"`
	// Unique token for instrument
	InstrumentToken int32 `json:"instrumentToken,omitempty"`
	// squareUp of the instrument
	SquareUp string `json:"squareUp,omitempty"`
	// serviceTax for instrument
	ServiceTax int32 `json:"serviceTax,omitempty"`
	// netBrokrage for instrument
	NetBrokrage int32 `json:"netBrokrage,omitempty"`
	// otherCharges for instrument
	OtherCharges int32 `json:"otherCharges,omitempty"`
	// serviceTaxOnOthers for instrument
	ServiceTaxOnOthers int32 `json:"serviceTaxOnOthers,omitempty"`
	// stampDuty for instrument
	StampDuty int32 `json:"stampDuty,omitempty"`
	// stt for instrument
	Stt int32 `json:"stt,omitempty"`
	// ISIN number
	ISIN string `json:"ISIN,omitempty"`
	// intraday charges
	Intraday int32 `json:"intraday,omitempty"`
}
