/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

type InlineResponse2003SuccessDebentures struct {
	MarketTransactionTotal              *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"marketTransactionTotal,omitempty"`
	OffMarketTransferInwardOutwardTotal *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"offMarketTransferInwardOutwardTotal,omitempty"`
	OffMarketTransferOutwardTotal       *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"offMarketTransferOutwardTotal,omitempty"`
	OffMarketsTransferInwardTotal       *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"offMarketsTransferInwardTotal,omitempty"`
	Total                               *InlineResponse2002SuccessDebenturesMarketTransactionTotal `json:"total,omitempty"`
	Details                             []InlineResponse2003SuccessDebenturesDetails               `json:"details,omitempty"`
}
