/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

type InlineResponse2004 struct {
	// Unique token for instrument
	InstrumentToken int32 `json:"instrumentToken,omitempty"`
	// instrument name of contract
	InstrumentName string `json:"instrumentName,omitempty"`
	// Amount of purchase
	Amount float64 `json:"amount,omitempty"`
	// Quantity of purchase
	Quantity float64 `json:"quantity,omitempty"`
	// rate of purchase
	Rate float64 `json:"rate,omitempty"`
	// Transaction date
	TransDate string `json:"transDate,omitempty"`
}
