/*
 * Portfolio - API
 *
 * This is a sample server for Kotak Trade API - Portfolio
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package portfolio

type PnlSchema struct {
	Equity     []PnlEquity     `json:"equity,omitempty"`
	Mutualfund []PnlMutualfund `json:"mutualfund,omitempty"`
	Derivative []PnlDerivative `json:"derivative,omitempty"`
	Currency   []PnlCurrency   `json:"currency,omitempty"`
	Commodity  []PnlCommodity  `json:"commodity,omitempty"`
}
