/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type LoginUseridBody struct {
	// Your KSEC userID
	Userid string `json:"userid,omitempty"`
	// Your KSEC password
	Password string `json:"password,omitempty"`
}
