/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

// Encryption method of sesitive data such as passwrd, AcccessCode, MPIN etc.
type InlineResponse200Encryption struct {
	// Type of Encryption.
	Type_ string `json:"type,omitempty"`
	// Key Applicable in case of RSA,AES.
	PublickKey string `json:"publickKey,omitempty"`
	// Applicable Key size of type of Encryption.
	KeySize int64 `json:"keySize,omitempty"`
}
