/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

// Service domain for Funds API.
type InlineResponse2003SuccessService struct {
	Host string  `json:"host,omitempty"`
	Port float64 `json:"port,omitempty"`
}
