/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

// Redirect Host where API's are expected to get executed..
type InlineResponse200Redirect struct {
	// Redirect Host for API's.
	Host string `json:"host,omitempty"`
	// Redirect Port for API's
	KeySize int64 `json:"keySize,omitempty"`
}
