/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type InlineResponse2003SuccessApiToken struct {
	Redirect *InlineResponse2003SuccessApiTokenRedirect `json:"redirect,omitempty"`
	// API token Session Id on Successful authenthetication of One time Token.
	SessionId string `json:"sessionId,omitempty"`
}
