/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type Model2FaBiometricBody struct {
	// Userid for which  access code validation
	Userid string `json:"userid,omitempty"`
	// Biometric flag for login
	Biometric string `json:"biometric,omitempty"`
}
