/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type Model2FaMpinBody struct {
	// Userid for which  access code validation
	Userid string `json:"userid,omitempty"`
	// mpin for login
	Mpin string `json:"mpin,omitempty"`
}
