/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

// Weblink Host where Weblinnk based API/URL to get executed...
type InlineResponse200Weblink struct {
	// Weblink Host for API's.
	Host string `json:"host,omitempty"`
	// Weblink Port for API's
	KeySize int64 `json:"keySize,omitempty"`
}
