/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type InlineResponse2001 struct {
	// one Time Token generated on successful authentication
	OneTimeToken string `json:"oneTimeToken,omitempty"`
	// Mpin eligibiity flag, Y for True and N for False
	Mpin string `json:"mpin,omitempty"`
	// Biometric eligibiity flag, Y for True and N for False
	Biometric string `json:"biometric,omitempty"`
	// Confirmation message on login.
	Message string `json:"message,omitempty"`
}
