/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type Model2FaAccesscodeBody struct {
	// Userid for which  access code validation
	Userid string `json:"userid,omitempty"`
	// Login access code received on email and mobile no
	AccessCode string `json:"accessCode,omitempty"`
}
