/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type InlineResponse2003Success struct {
	ApiToken  *InlineResponse2003SuccessApiToken  `json:"apiToken,omitempty"`
	Broadcast *InlineResponse2003SuccessBroadcast `json:"broadcast,omitempty"`
	// Valid Client account of Login User.
	ClientCode string `json:"clientCode,omitempty"`
	// Name of the Login User.
	ClientName string `json:"clientName,omitempty"`
	// Email Id of the User.
	EmailId         string   `json:"emailId,omitempty"`
	EnabledProducts []string `json:"enabledProducts,omitempty"`
	// Enabled Segments for Trading.
	EnabledSegments []string `json:"enabledSegments,omitempty"`
	// Login time of User.
	LoginTime  string                               `json:"loginTime,omitempty"`
	MarketData *InlineResponse2003SuccessMarketData `json:"marketData,omitempty"`
	// Registered contact details.
	PhoneNo  string                             `json:"phoneNo,omitempty"`
	Redirect *InlineResponse2003SuccessRedirect `json:"redirect,omitempty"`
	Search   *InlineResponse2003SuccessSearch   `json:"search,omitempty"`
	Service  *InlineResponse2003SuccessService  `json:"service,omitempty"`
	// Final Session Token .
	SessionToken string `json:"sessionToken,omitempty"`
	// STWT Disclamer Flag.
	StwtFlag string `json:"stwtFlag,omitempty"`
	// User Id of the user.
	UserId  string                            `json:"userId,omitempty"`
	Weblink *InlineResponse2003SuccessWeblink `json:"weblink,omitempty"`
}
