/*
 * Session-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package session

type InlineResponse2002 struct {
	// ID of the user
	UserId string `json:"userId,omitempty"`
	// Unique client code
	ClientCode string `json:"clientCode,omitempty"`
	// Full name of the client
	ClientName string `json:"clientName,omitempty"`
	// Email ID of the user
	EmailId string `json:"emailId,omitempty"`
	// Registered phone number of the user
	PhoneNo int32 `json:"phoneNo,omitempty"`
	// Enabled segments of the user - equity, currency etc
	EnabledSegments []string `json:"enabledSegments,omitempty"`
	// Enabled products for the user - normal, supermultiple etc
	EnabledProducts []string `json:"enabledProducts,omitempty"`
	// Access token required for trading calls
	SessionToken string `json:"sessionToken,omitempty"`
	// Public token required for broadcast session
	PublicToken string `json:"publicToken,omitempty"`
	// Login time of the user in epoch format
	LoginTime int64 `json:"loginTime,omitempty"`
}
