/*
 * ScripMaster-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package scriptmaster

type InlineResponse2001Success struct {
	Weblink string `json:"weblink,omitempty"`
}
